class AsdfAT0170 < Formula
  desc "Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more"
  homepage "https://asdf-vm.com/"
  url "https://github.com/asdf-vm/asdf.git",
      tag:      "v0.17.0",
      revision: "fc87e2270753683560fc70c0c1bc3a8d2232e7a1"
  license "MIT"

  depends_on "go" => :build
  depends_on "git"

  def install
    # build CLI
    system "go", "build", *std_go_args(output: bin/"asdf", ldflags: "-s -w"), "./cmd/asdf"

    # shell integrations
    libexec.install "asdf.sh", "asdf.fish", "asdf.ps1", "asdf.nu", "asdf.elv"

    # completions generated by the binary
    generate_completions_from_executable(bin/"asdf", "completion")
  end

  def caveats
    <<~EOS
      啟用 asdf（擇一）：
        Bash/Zsh:  . #{opt_libexec}/asdf.sh
        Fish:      source #{opt_libexec}/asdf.fish
        PowerShell:. #{opt_libexec}/asdf.ps1
        Nushell:   use #{opt_libexec}/asdf.nu
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/asdf --version")
  end
end
